In [1]:
import numpy as np

In [5]:
M = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

In [7]:
v = np.array([[1], [2], [3]])

In [21]:
M.shape

(3, 3)

In [19]:
v.shape

(3, 1)

In [14]:
v_single_dim = np.array([1, 2, 3])

In [18]:
v_single_dim.shape

(3,)

In [16]:
v+v

array([[2],
       [4],
       [6]])

In [17]:
3*v

array([[3],
       [6],
       [9]])

## Special Arrays

In [22]:
np.zeros((7, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
np.ones((1, 2))

array([[1., 1.]])

In [25]:
np.full((4, 4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.random.random((2, 2))

array([[0.51199519, 0.09045311],
       [0.50599632, 0.09888285]])

In [33]:
M[:2, 1:3]

array([[2, 3],
       [5, 6]])

## Multiplication

In [34]:
M.dot(v)

array([[14],
       [32],
       [50]])

In [36]:
v.T.dot(M)

array([[30, 36, 42]])

In [40]:
v1 = np.array([[3], [-3], [1]])

In [39]:
v2 = np.array([[4], [-9], [2]])

In [41]:
np.cross(v1, v2, axisa=0, axisb=0).T

array([[  3],
       [ -2],
       [-15]])

## Pandas integration

In [42]:
import pandas as pd

In [52]:
mat = np.random.random((5, 5))

In [53]:
pd.DataFrame(mat)

0         1         2         3         4
0  0.560809  0.685093  0.756510  0.731819  0.460722
1  0.214043  0.457473  0.333225  0.679061  0.069448
2  0.834988  0.781889  0.334577  0.881034  0.772980
3  0.463909  0.666500  0.749360  0.841561  0.767189
4  0.199361  0.951084  0.671919  0.479329  0.917413

In [54]:
matt = pd.DataFrame(mat.T)
matt

0         1         2         3         4
0  0.560809  0.214043  0.834988  0.463909  0.199361
1  0.685093  0.457473  0.781889  0.666500  0.951084
2  0.756510  0.333225  0.334577  0.749360  0.671919
3  0.731819  0.679061  0.881034  0.841561  0.479329
4  0.460722  0.069448  0.772980  0.767189  0.917413

In [56]:
matt2 = pd.DataFrame(mat).T
matt2

0         1         2         3         4
0  0.560809  0.214043  0.834988  0.463909  0.199361
1  0.685093  0.457473  0.781889  0.666500  0.951084
2  0.756510  0.333225  0.334577  0.749360  0.671919
3  0.731819  0.679061  0.881034  0.841561  0.479329
4  0.460722  0.069448  0.772980  0.767189  0.917413